{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import requests\n",
    "import math\n",
    "import csv\n",
    "import os\n",
    "import re\n",
    "\n",
    "# --正式开始爬虫--\n",
    "\n",
    "def getAlldownloadAddress(year_list, industry_list, out_put_file):\n",
    "    '''\n",
    "    year_list     : 年份（字符串格式）的列表，如['2010','2011','2012','2013']\n",
    "    industry_list : 行业（字符串格式）的列表，取自\n",
    "                                               (农、林、牧、渔业;\n",
    "                                                采矿业;\n",
    "                                                制造业;\n",
    "                                                电力、热力、燃气及水生产和供应业;\n",
    "                                                建筑业;\n",
    "                                                批发和零售业;\n",
    "                                                交通运输、仓储和邮政业;\n",
    "                                                住宿和餐饮业;\n",
    "                                                信息传输、软件和信息技术服务业;\n",
    "                                                房地产业;\n",
    "                                                租赁和商务服务业;\n",
    "                                                科学研究和技术服务业;\n",
    "                                                居民服务、修理和其他服务业;\n",
    "                                                教育;\n",
    "                                                卫生和社会工作;\n",
    "                                                文化、体育和娱乐业;\n",
    "                                                综合;)\n",
    "    out_put_file : 输出内容存放的文件夹目录\n",
    "    '''\n",
    "    \n",
    "    # 基本参数 - 固定\n",
    "    \"\"\"\n",
    "    *****************\n",
    "    固定配置，勿改\n",
    "    *****************\n",
    "    \"\"\"\n",
    "    URL = 'http://www.cninfo.com.cn/new/hisAnnouncement/query'\n",
    "    HEADER = {\n",
    "        'User-Agent': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',\n",
    "        'X-Requested-With': 'XMLHttpRequest'\n",
    "    }\n",
    "    MAX_PAGESIZE = 50\n",
    "    MAX_RELOAD_TIMES = 5\n",
    "    RESPONSE_TIMEOUT = 10\n",
    "    \n",
    "    for year_each in year_list:\n",
    "        \n",
    "        for industry_each in industry_list:\n",
    "            \n",
    "            # 基本参数 - 可改\n",
    "            \"\"\"\n",
    "            *****************\n",
    "            可改配置，酌情更改\n",
    "            *****************\n",
    "            \"\"\"\n",
    "            announcementYear = year_each\n",
    "            seDate = announcementYear+'-01-01~'+announcementYear+'-12-31'\n",
    "            trade = industry_each\n",
    "\n",
    "            # 第一次请求获得总条目数，用以计算页数\n",
    "            query = {\n",
    "                'pageNum': ''\n",
    "                ,'pageSize': MAX_PAGESIZE\n",
    "                ,'tabName': 'fulltext'\n",
    "                ,'column': 'szse'\n",
    "                ,'stock': ''\n",
    "                ,'searchkey': ''\n",
    "                ,'secid': ''\n",
    "                ,'plate': 'szmb'\n",
    "                ,'category': 'category_ndbg_szsh;'\n",
    "                ,'trade': trade\n",
    "                ,'seDate': seDate\n",
    "            }\n",
    "            r = requests.post(URL, query, HEADER, timeout=RESPONSE_TIMEOUT)\n",
    "            my_query = r.json()\n",
    "            total_page_num = math.ceil(my_query['totalAnnouncement']/MAX_PAGESIZE)\n",
    "\n",
    "            #  逐页抓取\n",
    "            result_list = []\n",
    "            for pageNum in range(1,total_page_num+1):\n",
    "                query = {\n",
    "                'pageNum': pageNum\n",
    "                ,'pageSize': MAX_PAGESIZE\n",
    "                ,'tabName': 'fulltext'\n",
    "                ,'column': 'szse'\n",
    "                ,'stock': ''\n",
    "                ,'searchkey': ''\n",
    "                ,'secid': ''\n",
    "                ,'plate': 'szmb'\n",
    "                ,'category': 'category_ndbg_szsh;'\n",
    "                ,'trade': trade\n",
    "                ,'seDate': seDate\n",
    "                }\n",
    "            #     r = requests.post(URL, query, HEADER, timeout=RESPONSE_TIMEOUT)\n",
    "\n",
    "                reloading = 0\n",
    "                while True:\n",
    "                    reloading += 1\n",
    "                    if reloading > MAX_RELOAD_TIMES:\n",
    "                        break\n",
    "            #         elif reloading > 1:\n",
    "            #             __sleeping(random.randint(5, 10))\n",
    "            #             print('... reloading: the ' + str(reloading) + ' round ...')\n",
    "                    try:\n",
    "                        r = requests.post(URL, query, HEADER, timeout=RESPONSE_TIMEOUT)\n",
    "                    except Exception as e:\n",
    "                        print(e)\n",
    "                        continue\n",
    "                    if r.status_code == requests.codes.ok and r.text != '':\n",
    "                        break\n",
    "                my_query = r.json()\n",
    "                r.close()\n",
    "\n",
    "                for each in my_query['announcements']:\n",
    "                    file_link = 'http://www.cninfo.com.cn/' + str(each['adjunctUrl'])\n",
    "                    file_name = str(each['secCode']) + str(each['secName']) + str(each['announcementTitle']) + file_link[-4:]\n",
    "                    result_list.append([file_name, file_link])\n",
    "                \n",
    "                print('Page%d/%d'% (pageNum,total_page_num),announcementYear,trade )\n",
    "        \n",
    "            out_put_file = out_put_file\n",
    "\n",
    "            for result in result_list:\n",
    "                year = re.findall('(20\\d\\d)年',result[0])[0]\n",
    "\n",
    "                if os.path.exists(out_put_file+str(year)):\n",
    "                    pass\n",
    "                else:\n",
    "                    os.makedirs(out_put_file+str(year))\n",
    "\n",
    "                output_csv_file = out_put_file+str(year)+'/'+trade+'.csv'\n",
    "                with open(output_csv_file, 'a', newline='', encoding='gb18030') as csv_out:\n",
    "                    writer = csv.writer(csv_out)\n",
    "                    writer.writerows([result])\n",
    "            print(announcementYear,trade)\n",
    "\n",
    "####### RUN ################################################################################################\n",
    "            \n",
    "getAlldownloadAddress(year_list     = [str(2010+i) for i in range(4)], \n",
    "                      industry_list = [\n",
    "                                        '农、林、牧、渔业',\n",
    "                                        '采矿业',\n",
    "                                        '制造业',\n",
    "                                        '电力、热力、燃气及水生产和供应业',\n",
    "                                        '建筑业',\n",
    "                                        '批发和零售业',\n",
    "                                        '交通运输、仓储和邮政业',\n",
    "                                        '住宿和餐饮业',\n",
    "                                        '信息传输、软件和信息技术服务业',\n",
    "                                        '房地产业',\n",
    "                                        '租赁和商务服务业',\n",
    "                                        '科学研究和技术服务业',\n",
    "                                        '居民服务、修理和其他服务业',\n",
    "                                        '教育',\n",
    "                                        '卫生和社会工作',\n",
    "                                        '文化、体育和娱乐业',\n",
    "                                        '综合'\n",
    "                                        ], \n",
    "                      out_put_file  = 'D:/report_pdf/')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
